# Generated by Django 4.0.1 on 2022-05-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
