# Generated by Django 4.0.1 on 2022-05-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
